package pyright

// From https://github.com/microsoft/pyright/blob/main/docs/configuration.md
var Rules = map[string]string{
	"strictListInference":                 "When inferring the type of a list, use strict type assumptions. For example, the expression [1, 'a', 3.4] could be inferred to be of type list[Any] or list[int | str | float]. If this setting is true, it will use the latter (stricter) type.",
	"strictDictionaryInference":           "When inferring the type of a dictionary’s keys and values, use strict type assumptions. For example, the expression {'a': 1, 'b': 'a'} could be inferred to be of type dict[str, Any] or dict[str, int | str]. If this setting is true, it will use the latter (stricter) type.",
	"strictSetInference":                  "When inferring the type of a set, use strict type assumptions. For example, the expression {1, 'a', 3.4} could be inferred to be of type set[Any] or set[int | str | float]. If this setting is true, it will use the latter (stricter) type.",
	"analyzeUnannotatedFunctions":         "Analyze and report errors for functions and methods that have no type annotations for input parameters or return types.",
	"strictParameterNoneValue":            "PEP 484 indicates that when a function parameter is assigned a default value of None, its type should implicitly be Optional even if the explicit type is not. When enabled, this rule requires that parameter type annotations use Optional explicitly in this case.",
	"enableTypeIgnoreComments":            "PEP 484 defines support for \"# type: ignore\" comments. This switch enables or disables support for these comments.",
	"deprecateTypingAliases":              "PEP 585 indicates that aliases to types in standard collections that were introduced solely to support generics are deprecated as of Python 3.9. This switch controls whether these are treated as deprecated. This applies only when pythonVersion is 3.9 or newer.",
	"enableExperimentalFeatures":          "Enables a set of experimental (mostly undocumented) features that correspond to proposed or exploratory changes to the Python typing standard. These features will likely change or be removed, so they should not be used except for experimentation purposes.",
	"disableBytesTypePromotions":          "Disables legacy behavior where bytearray and memoryview are considered subtypes of bytes. PEP 688 deprecates this behavior, but this switch is provided to restore the older behavior.",
	"reportGeneralTypeIssues":             "Generate or suppress diagnostics for general type inconsistencies, unsupported operations, argument/parameter mismatches, etc. This covers all of the basic type-checking rules not covered by other rules. It does not include syntax errors.",
	"reportPropertyTypeMismatch":          "Generate or suppress diagnostics for properties where the type of the value passed to the setter is not assignable to the value returned by the getter. Such mismatches violate the intended use of properties, which are meant to act like variables.",
	"reportFunctionMemberAccess":          "Generate or suppress diagnostics for non-standard member accesses for functions.",
	"reportMissingImports":                "Generate or suppress diagnostics for imports that have no corresponding imported python file or type stub file.",
	"reportMissingModuleSource":           "Generate or suppress diagnostics for imports that have no corresponding source file. This happens when a type stub is found, but the module source file was not found, indicating that the code may fail at runtime when using this execution environment. Type checking will be done using the type stub.",
	"reportInvalidTypeForm":               "Generate or suppress diagnostics for type annotations that use invalid type expression forms or are semantically invalid.",
	"reportMissingTypeStubs":              "Generate or suppress diagnostics for imports that have no corresponding type stub file (either a typeshed file or a custom type stub). The type checker requires type stubs to do its best job at analysis.",
	"reportImportCycles":                  "Generate or suppress diagnostics for cyclical import chains. These are not errors in Python, but they do slow down type analysis and often hint at architectural layering issues. Generally, they should be avoided.",
	"reportUnusedImport":                  "Generate or suppress diagnostics for an imported symbol that is not referenced within that file.",
	"reportUnusedClass":                   "Generate or suppress diagnostics for a class with a private name (starting with an underscore) that is not accessed.",
	"reportUnusedFunction":                "Generate or suppress diagnostics for a function or method with a private name (starting with an underscore) that is not accessed.",
	"reportUnusedVariable":                "Generate or suppress diagnostics for a variable that is not accessed.",
	"reportDuplicateImport":               "Generate or suppress diagnostics for an imported symbol or module that is imported more than once.",
	"reportWildcardImportFromLibrary":     "Generate or suppress diagnostics for a wildcard import from an external library. The use of this language feature is highly discouraged and can result in bugs when the library is updated.",
	"reportAbstractUsage":                 "Generate or suppress diagnostics for the attempted instantiate an abstract or protocol class or use of an abstract method.",
	"reportArgumentType":                  "Generate or suppress diagnostics for argument type incompatibilities when evaluating a call expression.",
	"reportAssertTypeFailure":             "Generate or suppress diagnostics for a type mismatch detected by the typing.assert_type call.",
	"reportAssignmentType":                "Generate or suppress diagnostics for assignment type incompatibility.",
	"reportAttributeAccessIssue":          "Generate or suppress diagnostics related to attribute accesses.",
	"reportCallIssue":                     "Generate or suppress diagnostics related to call expressions and arguments passed to a call target.",
	"reportInconsistentOverload":          "Generate or suppress diagnostics for an overloaded function that has overload signatures that are inconsistent with each other or with the implementation.",
	"reportIndexIssue":                    "Generate or suppress diagnostics related to index operations and expressions.",
	"reportInvalidTypeArguments":          "Generate or suppress diagnostics for invalid type argument usage.",
	"reportNoOverloadImplementation":      "Generate or suppress diagnostics for an overloaded function or method if the implementation is not provided.",
	"reportOperatorIssue":                 "Generate or suppress diagnostics related to the use of unary or binary operators (like * or not).",
	"reportOptionalSubscript":             "Generate or suppress diagnostics for an attempt to subscript (index) a variable with an Optional type.",
	"reportOptionalMemberAccess":          "Generate or suppress diagnostics for an attempt to access a member of a variable with an Optional type.",
	"reportOptionalCall":                  "Generate or suppress diagnostics for an attempt to call a variable with an Optional type.",
	"reportOptionalIterable":              "Generate or suppress diagnostics for an attempt to use an Optional type as an iterable value (e.g. within a for statement).",
	"reportOptionalContextManager":        "Generate or suppress diagnostics for an attempt to use an Optional type as a context manager (as a parameter to a with statement).",
	"reportOptionalOperand":               "Generate or suppress diagnostics for an attempt to use an Optional type as an operand to a unary operator (like ~ or not) or the left-hand operator of a binary operator (like *, ==, or).",
	"reportRedeclaration":                 "Generate or suppress diagnostics for a symbol that has more than one type declaration.",
	"reportReturnType":                    "Generate or suppress diagnostics related to function return type compatibility.",
	"reportTypedDictNotRequiredAccess":    "Generate or suppress diagnostics for an attempt to access a non-required field within a TypedDict without first checking whether it is present.",
	"reportUntypedFunctionDecorator":      "Generate or suppress diagnostics for function decorators that have no type annotations. These obscure the function type, defeating many type analysis features.",
	"reportUntypedClassDecorator":         "Generate or suppress diagnostics for class decorators that have no type annotations. These obscure the class type, defeating many type analysis features.",
	"reportUntypedBaseClass":              "Generate or suppress diagnostics for base classes whose type cannot be determined statically. These obscure the class type, defeating many type analysis features.",
	"reportUntypedNamedTuple":             "Generate or suppress diagnostics when “namedtuple” is used rather than “NamedTuple”. The former contains no type information, whereas the latter does.",
	"reportPrivateUsage":                  "Generate or suppress diagnostics for incorrect usage of private or protected variables or functions. Protected class members begin with a single underscore (“_”) and can be accessed only by subclasses. Private class members begin with a double underscore but do not end in a double underscore and can be accessed only within the declaring class. Variables and functions declared outside of a class are considered private if their names start with either a single or double underscore, and they cannot be accessed outside of the declaring module.",
	"reportTypeCommentUsage":              "Prior to Python 3.5, the grammar did not support type annotations, so types needed to be specified using “type comments”. Python 3.5 eliminated the need for function type comments, and Python 3.6 eliminated the need for variable type comments. Future versions of Python will likely deprecate all support for type comments. If enabled, this check will flag any type comment usage unless it is required for compatibility with the specified language version.",
	"reportPrivateImportUsage":            "Generate or suppress diagnostics for use of a symbol from a \"py.typed\" module that is not meant to be exported from that module.",
	"reportConstantRedefinition":          "Generate or suppress diagnostics for attempts to redefine variables whose names are all-caps with underscores and numerals.",
	"reportDeprecated":                    "Generate or suppress diagnostics for use of a class or function that has been marked as deprecated.",
	"reportIncompatibleMethodOverride":    "Generate or suppress diagnostics for methods that override a method of the same name in a base class in an incompatible manner (wrong number of parameters, incompatible parameter types, or incompatible return type).",
	"reportIncompatibleVariableOverride":  "Generate or suppress diagnostics for class variable declarations that override a symbol of the same name in a base class with a type that is incompatible with the base class symbol type.",
	"reportInconsistentConstructor":       "Generate or suppress diagnostics when an __init__ method signature is inconsistent with a __new__ signature.",
	"reportOverlappingOverload":           "Generate or suppress diagnostics for function overloads that overlap in signature and obscure each other or have incompatible return types.",
	"reportPossiblyUnboundVariable":       "Generate or suppress diagnostics for variables that are possibly unbound on some code paths.",
	"reportMissingSuperCall":              "Generate or suppress diagnostics for __init__, __init_subclass__, __enter__ and __exit__ methods in a subclass that fail to call through to the same-named method on a base class.",
	"reportUninitializedInstanceVariable": "Generate or suppress diagnostics for instance variables within a class that are not initialized or declared within the class body or the __init__ method.",
	"reportInvalidStringEscapeSequence":   "Generate or suppress diagnostics for invalid escape sequences used within string literals. The Python specification indicates that such sequences will generate a syntax error in future versions.",
	"reportUnknownParameterType":          "Generate or suppress diagnostics for input or return parameters for functions or methods that have an unknown type.",
	"reportUnknownArgumentType":           "Generate or suppress diagnostics for call arguments for functions or methods that have an unknown type.",
	"reportUnknownLambdaType":             "Generate or suppress diagnostics for input or return parameters for lambdas that have an unknown type.",
	"reportUnknownVariableType":           "Generate or suppress diagnostics for variables that have an unknown type.",
	"reportUnknownMemberType":             "Generate or suppress diagnostics for class or instance variables that have an unknown type.",
	"reportMissingParameterType":          "Generate or suppress diagnostics for input parameters for functions or methods that are missing a type annotation. The self and cls parameters used within methods are exempt from this check.",
	"reportMissingTypeArgument":           "Generate or suppress diagnostics when a generic class is used without providing explicit or implicit type arguments.",
	"reportInvalidTypeVarUse":             "Generate or suppress diagnostics when a TypeVar is used inappropriately (e.g. if a TypeVar appears only once) within a generic function signature.",
	"reportCallInDefaultInitializer":      "Generate or suppress diagnostics for function calls, list expressions, set expressions, or dictionary expressions within a default value initialization expression. Such calls can mask expensive operations that are performed at module initialization time.",
	"reportUnnecessaryIsInstance":         "Generate or suppress diagnostics for isinstance or issubclass calls where the result is statically determined to be always true. Such calls are often indicative of a programming error.",
	"reportUnnecessaryCast":               "Generate or suppress diagnostics for cast calls that are statically determined to be unnecessary. Such calls are sometimes indicative of a programming error.",
	"reportUnnecessaryComparison":         "Generate or suppress diagnostics for == or != comparisons or other conditional expressions that are statically determined to always evaluate to False or True. Such comparisons are sometimes indicative of a programming error.",
	"reportUnnecessaryContains":           "Generate or suppress diagnostics for in operations that are statically determined to always evaluate to False or True. Such operations are sometimes indicative of a programming error.",
	"reportAssertAlwaysTrue":              "Generate or suppress diagnostics for assert statement that will provably always assert. This can be indicative of a programming error.",
	"reportSelfClsParameterName":          "Generate or suppress diagnostics for a missing or misnamed “self” parameter in instance methods and “cls” parameter in class methods. Instance methods in metaclasses (classes that derive from “type”) are allowed to use “cls” for instance methods.",
	"reportImplicitStringConcatenation":   "Generate or suppress diagnostics for two or more string literals that follow each other, indicating an implicit concatenation. This is considered a bad practice and often masks bugs such as missing commas.",
	"reportUndefinedVariable":             "Generate or suppress diagnostics for undefined variables.",
	"reportUnboundVariable":               "Generate or suppress diagnostics for unbound variables.",
	"reportUnhashable":                    "Generate or suppress diagnostics for the use of an unhashable object in a container that requires hashability.",
	"reportInvalidStubStatement":          "Generate or suppress diagnostics for statements that are syntactically correct but have no purpose within a type stub file.",
	"reportIncompleteStub":                "Generate or suppress diagnostics for a module-level __getattr__ call in a type stub file, indicating that it is incomplete.",
	"reportUnsupportedDunderAll":          "Generate or suppress diagnostics for statements that define or manipulate __all__ in a way that is not allowed by a static type checker, thus rendering the contents of __all__ to be unknown or incorrect. Also reports names within the __all__ list that are not present in the module namespace.",
	"reportUnusedCallResult":              "Generate or suppress diagnostics for call statements whose return value is not used in any way and is not None.",
	"reportUnusedCoroutine":               "Generate or suppress diagnostics for call statements whose return value is not used in any way and is a Coroutine. This identifies a common error where an await keyword is mistakenly omitted.",
	"reportUnusedExcept":                  "Generate or suppress diagnostics for an except clause that will never be reached.",
	"reportUnusedExpression":              "Generate or suppress diagnostics for simple expressions whose results are not used in any way.",
	"reportUnnecessaryTypeIgnoreComment":  "Generate or suppress diagnostics for a # type: ignore or # pyright: ignore comment that would have no effect if removed.",
	"reportMatchNotExhaustive":            "Generate or suppress diagnostics for a match statement that does not provide cases that exhaustively match against all potential types of the target expression.",
	"reportImplicitOverride":              "Generate or suppress diagnostics for overridden methods in a class that are missing an explicit @override decorator.",
	"reportShadowedImports":               "Generate or suppress diagnostics for files that are overriding a module in the stdlib.",
}
