// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package phpCsFixer

import "encoding/json"
import "fmt"

type PhpCsFixerSchemaJson struct {
	// Files corresponds to the JSON schema field "files".
	Files []PhpCsFixerSchemaJsonFilesElem `json:"files" yaml:"files" mapstructure:"files"`

	// Memory corresponds to the JSON schema field "memory".
	Memory float64 `json:"memory" yaml:"memory" mapstructure:"memory"`

	// Time corresponds to the JSON schema field "time".
	Time PhpCsFixerSchemaJsonTime `json:"time" yaml:"time" mapstructure:"time"`
}

type PhpCsFixerSchemaJsonFilesElem struct {
	// AppliedFixers corresponds to the JSON schema field "appliedFixers".
	AppliedFixers []string `json:"appliedFixers,omitempty" yaml:"appliedFixers,omitempty" mapstructure:"appliedFixers,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PhpCsFixerSchemaJsonFilesElem) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in PhpCsFixerSchemaJsonFilesElem: required")
	}
	type Plain PhpCsFixerSchemaJsonFilesElem
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = PhpCsFixerSchemaJsonFilesElem(plain)
	return nil
}

type PhpCsFixerSchemaJsonTime struct {
	// Total corresponds to the JSON schema field "total".
	Total float64 `json:"total" yaml:"total" mapstructure:"total"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PhpCsFixerSchemaJsonTime) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["total"]; raw != nil && !ok {
		return fmt.Errorf("field total in PhpCsFixerSchemaJsonTime: required")
	}
	type Plain PhpCsFixerSchemaJsonTime
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = PhpCsFixerSchemaJsonTime(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PhpCsFixerSchemaJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["files"]; raw != nil && !ok {
		return fmt.Errorf("field files in PhpCsFixerSchemaJson: required")
	}
	if _, ok := raw["memory"]; raw != nil && !ok {
		return fmt.Errorf("field memory in PhpCsFixerSchemaJson: required")
	}
	if _, ok := raw["time"]; raw != nil && !ok {
		return fmt.Errorf("field time in PhpCsFixerSchemaJson: required")
	}
	type Plain PhpCsFixerSchemaJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = PhpCsFixerSchemaJson(plain)
	return nil
}
